import { NextResponse } from "next/server";
import { LocalObjectStore, verifyLocalSignature } from "@/lib/server/storage";
import { MAX_UPLOAD_BYTES } from "@/lib/server/storage";
import { objectStorageConfigured } from "@/lib/server/config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The endpoint half of the local object store.
 *
 * Only reachable when R2 is not configured. It exists so Photobooth and Snap
 * Hunt work in local development with no Cloudflare account, the same reason
 * `LocalRoomTransport` exists — and so the upload path can be tested for real
 * rather than mocked.
 *
 * The signature is the whole authorization: it covers the key, the method and
 * the expiry, so a URL cannot be edited to reach another object, reused for the
 * wrong verb, or replayed after it lapses. No session is consulted, because the
 * URL *is* the capability — exactly as with an R2 presigned URL. What decides
 * whether a caller gets one of these is `/api/media`, which does check.
 */

/**
 * The type this object was stored as, from the extension the server chose.
 *
 * Not from the request, and not sniffed: the upload path already confirmed the
 * bytes match an allowed image format, and the key it minted records which one.
 * Anything unrecognised is served as bytes rather than guessed at.
 */
function contentTypeFor(key: string): string {
  const extension = key.slice(key.lastIndexOf(".") + 1).toLowerCase();
  return (
    { jpg: "image/jpeg", jpeg: "image/jpeg", png: "image/png", webp: "image/webp" }[extension] ??
    "application/octet-stream"
  );
}

function readParams(request: Request) {
  const url = new URL(request.url);
  return {
    key: url.searchParams.get("key") ?? "",
    expires: Number(url.searchParams.get("expires") ?? 0),
    sig: url.searchParams.get("sig") ?? "",
  };
}

export async function PUT(request: Request) {
  if (objectStorageConfigured()) return NextResponse.json({ error: "Not found." }, { status: 404 });

  const { key, expires, sig } = readParams(request);
  if (!verifyLocalSignature(key, "PUT", expires, sig)) {
    return NextResponse.json({ error: "That upload link is not valid." }, { status: 403 });
  }

  const declared = Number(request.headers.get("content-length") ?? 0);
  if (declared > MAX_UPLOAD_BYTES) {
    return NextResponse.json({ error: "Too large." }, { status: 413 });
  }

  const body = new Uint8Array(await request.arrayBuffer());
  if (body.byteLength > MAX_UPLOAD_BYTES) {
    return NextResponse.json({ error: "Too large." }, { status: 413 });
  }

  try {
    await new LocalObjectStore().put(key, body);
  } catch {
    // `put` refuses a key that escapes the storage root. Keys are generated by
    // the server so this cannot happen — which is why it is checked.
    return NextResponse.json({ error: "Refused." }, { status: 400 });
  }

  return new NextResponse(null, { status: 200 });
}

export async function GET(request: Request) {
  if (objectStorageConfigured()) return NextResponse.json({ error: "Not found." }, { status: 404 });

  const { key, expires, sig } = readParams(request);
  if (!verifyLocalSignature(key, "GET", expires, sig)) {
    return NextResponse.json({ error: "That link is not valid." }, { status: 403 });
  }

  const bytes = await new LocalObjectStore().get(key).catch(() => null);
  if (!bytes) return NextResponse.json({ error: "Not found." }, { status: 404 });

  return new NextResponse(Buffer.from(bytes), {
    status: 200,
    headers: {
      "content-type": contentTypeFor(key),
      // Whatever this file turns out to be, the browser must treat it as the
      // type declared above. Without this a stored object that a sniffer reads
      // as HTML would run as a same-origin page.
      "x-content-type-options": "nosniff",
      // And it is never a page: an image the browser refuses to render should
      // download, not execute.
      "content-disposition": "inline",
      "cache-control": "private, max-age=900",
    },
  });
}
