export type PromptCategory =
  | "funny"
  | "cute"
  | "embarrassing"
  | "relationship"
  | "chaotic"
  | "flirty";

/** Chill = safe anywhere. Bold = you'll feel it. Chaotic = still harmless. */
export type PromptIntensity = "chill" | "bold" | "chaotic";

export interface Prompt {
  id: string;
  text: string;
  category: PromptCategory;
  intensity: PromptIntensity;
}

export const PROMPT_INTENSITIES: {
  id: PromptIntensity;
  label: string;
  blurb: string;
}[] = [
  { id: "chill", label: "Chill", blurb: "nothing you'd regret" },
  { id: "bold", label: "Bold", blurb: "a bit of nerve required" },
  { id: "chaotic", label: "Chaotic", blurb: "silly, never cruel" },
];

export const TRUTHS: Prompt[] = [
  // chill
  { id: "t01", text: "What's the first thing you noticed about me?", category: "cute", intensity: "chill" },
  { id: "t02", text: "What's a small thing I do that you'd miss?", category: "cute", intensity: "chill" },
  { id: "t03", text: "What's the last thing you googled?", category: "funny", intensity: "chill" },
  { id: "t04", text: "What's the most useless thing you know a lot about?", category: "funny", intensity: "chill" },
  { id: "t05", text: "What's your comfort film, and how many times?", category: "cute", intensity: "chill" },
  { id: "t06", text: "What's something you pretend to like?", category: "funny", intensity: "chill" },
  { id: "t07", text: "What's the best compliment you've ever been given?", category: "cute", intensity: "chill" },
  { id: "t08", text: "What's your most-used emoji, and what does it actually mean?", category: "funny", intensity: "chill" },
  { id: "t09", text: "What's a food combination you love that people judge?", category: "funny", intensity: "chill" },
  { id: "t10", text: "What's the pettiest thing that ruins your day?", category: "funny", intensity: "chill" },
  { id: "t11", text: "What's something you were weirdly good at as a kid?", category: "cute", intensity: "chill" },
  { id: "t12", text: "What's a rule you follow that nobody asked you to?", category: "funny", intensity: "chill" },
  { id: "t13", text: "What's the last thing that made you laugh out loud alone?", category: "funny", intensity: "chill" },
  { id: "t14", text: "What's your go-to lie when you don't want to go out?", category: "funny", intensity: "chill" },
  { id: "t15", text: "What's the nicest thing a stranger has done for you?", category: "cute", intensity: "chill" },
  { id: "t16", text: "What's a talent you'd bring to a group project?", category: "funny", intensity: "chill" },
  { id: "t17", text: "What's the most you've ever spent on something silly?", category: "funny", intensity: "chill" },
  { id: "t18", text: "What's a song you'd be embarrassed to have on repeat?", category: "embarrassing", intensity: "chill" },
  { id: "t19", text: "What's your most irrational fear?", category: "funny", intensity: "chill" },
  { id: "t20", text: "What's the best thing about today?", category: "cute", intensity: "chill" },
  { id: "t21", text: "What's a hill you'd genuinely die on?", category: "funny", intensity: "chill" },
  { id: "t22", text: "What do you do that you'd be annoyed by in someone else?", category: "funny", intensity: "chill" },
  { id: "t23", text: "What's the last thing you saved a photo of?", category: "funny", intensity: "chill" },
  { id: "t24", text: "What's something you've never learned to do properly?", category: "funny", intensity: "chill" },
  { id: "t25", text: "What's a compliment you'd give me right now, no thinking?", category: "cute", intensity: "chill" },
  { id: "t26", text: "What's the weirdest thing in your fridge?", category: "funny", intensity: "chill" },
  { id: "t27", text: "What's your worst habit when nobody's watching?", category: "embarrassing", intensity: "chill" },
  { id: "t28", text: "What's a small win you had this week?", category: "cute", intensity: "chill" },
  { id: "t29", text: "What's the most overrated thing everyone loves?", category: "funny", intensity: "chill" },
  { id: "t30", text: "What would your autobiography be called?", category: "funny", intensity: "chill" },
  { id: "t31", text: "What's the last time you were properly proud of yourself?", category: "cute", intensity: "chill" },
  { id: "t32", text: "What's something you own that you'd never replace?", category: "cute", intensity: "chill" },
  { id: "t33", text: "What's a thing you say too often?", category: "funny", intensity: "chill" },

  // bold
  { id: "t34", text: "What's a compliment you've thought about me but never said?", category: "relationship", intensity: "bold" },
  { id: "t35", text: "When did you last pretend to be fine?", category: "relationship", intensity: "bold" },
  { id: "t36", text: "What's something you changed your mind about because of me?", category: "relationship", intensity: "bold" },
  { id: "t37", text: "What's the most embarrassing thing in your camera roll?", category: "embarrassing", intensity: "bold" },
  { id: "t38", text: "What's a habit of mine you've quietly adopted?", category: "relationship", intensity: "bold" },
  { id: "t39", text: "What do you think I'm underestimating about myself?", category: "relationship", intensity: "bold" },
  { id: "t40", text: "What's a text you typed to me and deleted?", category: "relationship", intensity: "bold" },
  { id: "t41", text: "Who did you tell about me first, and what did you say?", category: "relationship", intensity: "bold" },
  { id: "t42", text: "What's a plan you're scared to say out loud?", category: "relationship", intensity: "bold" },
  { id: "t43", text: "What's the most childish thing you still do?", category: "embarrassing", intensity: "bold" },
  { id: "t44", text: "What's the worst thing you've ever worn confidently?", category: "embarrassing", intensity: "bold" },
  { id: "t45", text: "What's a lie you told that got out of hand?", category: "embarrassing", intensity: "bold" },
  { id: "t46", text: "What's something you did as a teenager that you'd never admit to your family?", category: "embarrassing", intensity: "bold" },
  { id: "t47", text: "When did you last cry, and what was it actually about?", category: "relationship", intensity: "bold" },
  { id: "t48", text: "What's the most jealous you've ever been?", category: "relationship", intensity: "bold" },
  { id: "t49", text: "What's a thing about me you found annoying at first and now like?", category: "relationship", intensity: "bold" },
  { id: "t50", text: "What's the biggest risk you've taken that nobody knows about?", category: "relationship", intensity: "bold" },
  { id: "t51", text: "What's something you'd change about how we handle arguments?", category: "relationship", intensity: "bold" },
  { id: "t52", text: "What's the most awkward date you've been on?", category: "embarrassing", intensity: "bold" },
  { id: "t53", text: "What's a moment you knew you'd remember forever?", category: "relationship", intensity: "bold" },
  { id: "t54", text: "What's something you want more of but haven't asked for?", category: "relationship", intensity: "bold" },
  { id: "t55", text: "What did you assume about me that turned out to be wrong?", category: "relationship", intensity: "bold" },
  { id: "t56", text: "What's your most embarrassing crush, ever?", category: "embarrassing", intensity: "bold" },
  { id: "t57", text: "What's the worst advice you've ever confidently given?", category: "embarrassing", intensity: "bold" },
  { id: "t58", text: "What's a thing you're pretending not to want?", category: "relationship", intensity: "bold" },
  { id: "t59", text: "What's the last thing you were properly wrong about with me?", category: "relationship", intensity: "bold" },
  { id: "t60", text: "What's a compliment you struggle to believe?", category: "relationship", intensity: "bold" },
  { id: "t61", text: "What's the pettiest reason you've ever ended something?", category: "embarrassing", intensity: "bold" },
  { id: "t62", text: "What do you think I'd be most surprised to learn about you?", category: "relationship", intensity: "bold" },
  { id: "t63", text: "What's the most nervous you've been around me?", category: "flirty", intensity: "bold" },
  { id: "t64", text: "What's something you did purely to impress me?", category: "flirty", intensity: "bold" },
  { id: "t65", text: "What's a fantasy holiday you'd take if I couldn't come?", category: "funny", intensity: "bold" },
  { id: "t66", text: "What's the thing you'd want said at your leaving party?", category: "relationship", intensity: "bold" },

  // chaotic
  { id: "t67", text: "Read out your last five sent messages.", category: "chaotic", intensity: "chaotic" },
  { id: "t68", text: "Show your screen time and defend the top app.", category: "chaotic", intensity: "chaotic" },
  { id: "t69", text: "Open your camera roll to a random photo and explain it.", category: "chaotic", intensity: "chaotic" },
  { id: "t70", text: "What's the worst thing you've ever said out loud?", category: "chaotic", intensity: "chaotic" },
  { id: "t71", text: "Read the last thing you typed into a search bar.", category: "chaotic", intensity: "chaotic" },
  { id: "t72", text: "What's a secret you've kept for someone else that you'd love to tell?", category: "chaotic", intensity: "chaotic" },
  { id: "t73", text: "Show the oldest photo on your phone and explain the situation.", category: "chaotic", intensity: "chaotic" },
  { id: "t74", text: "What's your most-played song? No editing.", category: "chaotic", intensity: "chaotic" },
  { id: "t75", text: "What's the last thing you said about me to someone else?", category: "chaotic", intensity: "chaotic" },
  { id: "t76", text: "Read out your most recent note in your notes app.", category: "chaotic", intensity: "chaotic" },
  { id: "t77", text: "What's the worst thing you've done that you got away with?", category: "chaotic", intensity: "chaotic" },
  { id: "t78", text: "Who's the last person you stalked online, and why?", category: "chaotic", intensity: "chaotic" },
  { id: "t79", text: "What's the biggest thing you've hidden from your family?", category: "chaotic", intensity: "chaotic" },
  { id: "t80", text: "What's an opinion you'd get cancelled for at a dinner party?", category: "chaotic", intensity: "chaotic" },
  { id: "t81", text: "What's the most money you've wasted in one go?", category: "chaotic", intensity: "chaotic" },
  { id: "t82", text: "What's the pettiest revenge you've ever taken?", category: "chaotic", intensity: "chaotic" },
  { id: "t83", text: "Describe your worst haircut in full detail.", category: "chaotic", intensity: "chaotic" },
  { id: "t84", text: "What's the strangest thing you've done alone?", category: "chaotic", intensity: "chaotic" },
  { id: "t85", text: "Who would you swap lives with for a week, and what would you do first?", category: "chaotic", intensity: "chaotic" },

  // flirty
  { id: "t86", text: "What's the most attractive thing I do without noticing?", category: "flirty", intensity: "bold" },
  { id: "t87", text: "When did you first want to kiss me?", category: "flirty", intensity: "bold" },
  { id: "t88", text: "What's your favourite thing I wear?", category: "flirty", intensity: "chill" },
  { id: "t89", text: "What makes you feel most wanted?", category: "flirty", intensity: "bold" },
  { id: "t90", text: "What's the best kiss you've had — details optional.", category: "flirty", intensity: "bold" },
  { id: "t91", text: "What would your ideal night in with me look like, in detail?", category: "flirty", intensity: "bold" },
  { id: "t92", text: "What's a compliment about me you've only said to other people?", category: "flirty", intensity: "bold" },
  { id: "t93", text: "What's the flirtiest thing you've ever done badly?", category: "flirty", intensity: "chill" },
  { id: "t94", text: "What's something small I do that you find ridiculously attractive?", category: "flirty", intensity: "bold" },
  { id: "t95", text: "What would you want more of, if asking were easy?", category: "flirty", intensity: "bold" },
  { id: "t96", text: "What's the most romantic thing you've ever planned?", category: "flirty", intensity: "chill" },
  { id: "t97", text: "What's a nickname for me you've thought but never used?", category: "flirty", intensity: "chill" },
  { id: "t98", text: "Where's your favourite place to be kissed?", category: "flirty", intensity: "bold" },
  { id: "t99", text: "What did you think about me the first night we spent together?", category: "flirty", intensity: "bold" },
  { id: "t100", text: "What's the thing you'd never get bored of about me?", category: "flirty", intensity: "chill" },
];

export const DARES: Prompt[] = [
  // chill — doable in any room, no props
  { id: "d01", text: "Do your best impression of me for twenty seconds.", category: "funny", intensity: "chill" },
  { id: "d02", text: "Say something you like about me without using the word 'nice'.", category: "cute", intensity: "chill" },
  { id: "d03", text: "Give me a compliment in a terrible accent.", category: "funny", intensity: "chill" },
  { id: "d04", text: "Give a thirty-second acceptance speech for something completely ordinary you did today. Thank people.", category: "funny", intensity: "chill" },
  { id: "d05", text: "Narrate the last five minutes of this room as a nature documentary. Whisper it.", category: "funny", intensity: "chill" },
  { id: "d06", text: "Make up a two-line song about our worst plan ever.", category: "funny", intensity: "chill" },
  { id: "d07", text: "Say the alphabet backwards. Any mistake, start again.", category: "funny", intensity: "chill" },
  { id: "d08", text: "Talk for one minute about something you know nothing about, confidently.", category: "funny", intensity: "chill" },
  { id: "d09", text: "Send the third-oldest photo in your camera roll.", category: "embarrassing", intensity: "chill" },
  { id: "d10", text: "Pick any object in the room and sell it to me as a luxury item. Sixty seconds. Use the word 'crafted'.", category: "funny", intensity: "chill" },
  { id: "d11", text: "Recreate a photo of us from memory, right now, with your body.", category: "funny", intensity: "chill" },
  { id: "d12", text: "Narrate what I'm doing like a sports commentator for thirty seconds.", category: "funny", intensity: "chill" },
  { id: "d13", text: "Say three true things about me in the voice of a game show host.", category: "cute", intensity: "chill" },
  { id: "d14", text: "Deliver a breaking-news report about the last thing that happened in this room. Full anchor voice.", category: "funny", intensity: "chill" },
  { id: "d15", text: "Give a sixty-second TED talk on your most useless opinion.", category: "funny", intensity: "chill" },
  { id: "d16", text: "Sing your text messages for the next minute.", category: "funny", intensity: "chill" },
  { id: "d17", text: "Give a motivational half-time team talk to an object of my choosing. It is losing badly.", category: "funny", intensity: "chill" },
  { id: "d18", text: "Do an impression of how I answer the phone.", category: "funny", intensity: "chill" },
  { id: "d19", text: "Compliment three objects in this room, sincerely.", category: "funny", intensity: "chill" },
  { id: "d20", text: "Make the face you make when you're pretending to listen.", category: "funny", intensity: "chill" },
  { id: "d21", text: "Do a dramatic reading of the nearest set of instructions or label.", category: "funny", intensity: "chill" },
  { id: "d22", text: "Describe your day using only sound effects. I have to guess what happened.", category: "funny", intensity: "chill" },
  { id: "d23", text: "Give me a two-minute massage. No talking.", category: "cute", intensity: "chill" },
  { id: "d24", text: "Tell me the story of us in exactly ten words.", category: "cute", intensity: "chill" },
  { id: "d25", text: "Do a job interview for a role you'd be catastrophically bad at. I'm interviewing.", category: "funny", intensity: "chill" },
  { id: "d26", text: "Make up a rule for this game. We both have to follow it for two rounds.", category: "chaotic", intensity: "chill" },
  { id: "d27", text: "Speak in questions only until your next turn.", category: "funny", intensity: "chill" },
  { id: "d28", text: "Do an impression of the last person who annoyed you.", category: "funny", intensity: "chill" },
  { id: "d29", text: "Say something that would make past-you extremely confused.", category: "funny", intensity: "chill" },
  { id: "d30", text: "Give me your best pep talk for something I'm avoiding.", category: "cute", intensity: "chill" },
  { id: "d31", text: "Perform a magic trick. It does not have to work — but the patter has to be excellent.", category: "funny", intensity: "chill" },
  { id: "d32", text: "Describe what you're wearing as a fashion critic.", category: "funny", intensity: "chill" },
  { id: "d33", text: "Hold a plank while telling me something you're grateful for.", category: "funny", intensity: "chill" },

  // bold
  { id: "d34", text: "Let me pick your profile picture for the next hour.", category: "chaotic", intensity: "bold" },
  { id: "d35", text: "Text a friend a single mysterious emoji, no context.", category: "chaotic", intensity: "bold" },
  { id: "d36", text: "Read your last five sent messages out loud.", category: "embarrassing", intensity: "bold" },
  { id: "d37", text: "Post the worst photo of yourself you can find to your close friends.", category: "chaotic", intensity: "bold" },
  { id: "d38", text: "Let me write a message from your phone. You can read it first.", category: "chaotic", intensity: "bold" },
  { id: "d39", text: "Call the next person in your recent list and compliment them, then hang up.", category: "chaotic", intensity: "bold" },
  { id: "d40", text: "Say the most sincere thing you've thought about me today, out loud, looking at me.", category: "cute", intensity: "bold" },
  { id: "d41", text: "Show me your most recent search history entry.", category: "embarrassing", intensity: "bold" },
  { id: "d42", text: "Let me choose what you wear tomorrow. One item.", category: "chaotic", intensity: "bold" },
  { id: "d43", text: "Record a ten-second voice note singing, and keep it.", category: "embarrassing", intensity: "bold" },
  { id: "d44", text: "Tell me the thing you almost said earlier and didn't.", category: "relationship", intensity: "bold" },
  { id: "d45", text: "Send a message to someone you've been meaning to text for weeks.", category: "cute", intensity: "bold" },
  { id: "d46", text: "Let me look at your last three photos. No deleting first.", category: "embarrassing", intensity: "bold" },
  { id: "d47", text: "Do an impression of me being annoyed. Be accurate.", category: "funny", intensity: "bold" },
  { id: "d48", text: "Say three things you find attractive about me, no hedging.", category: "flirty", intensity: "bold" },
  { id: "d49", text: "Set your alarm label to something I choose for a week.", category: "chaotic", intensity: "bold" },
  { id: "d50", text: "Tell me a secret you were planning to keep for at least another month.", category: "relationship", intensity: "bold" },
  { id: "d51", text: "Make a genuine apology for something small you've never apologised for.", category: "relationship", intensity: "bold" },
  { id: "d52", text: "Let me ask you one question you have to answer completely honestly.", category: "relationship", intensity: "bold" },
  { id: "d53", text: "Do a two-minute stand-up set about our relationship.", category: "funny", intensity: "bold" },
  { id: "d54", text: "Show me the last thing you screenshotted and explain why.", category: "embarrassing", intensity: "bold" },
  { id: "d55", text: "Give me a genuine, detailed compliment for a full minute without stopping.", category: "cute", intensity: "bold" },
  { id: "d56", text: "Let me name one thing you have to do this week. Reasonable only.", category: "chaotic", intensity: "bold" },
  { id: "d57", text: "Recreate your worst dance move from a night out.", category: "embarrassing", intensity: "bold" },
  { id: "d58", text: "Tell me about the moment you knew you liked me.", category: "flirty", intensity: "bold" },
  { id: "d59", text: "Write me a two-line poem, out loud, right now.", category: "cute", intensity: "bold" },
  { id: "d60", text: "Do your best impression of your own mother or father.", category: "funny", intensity: "bold" },
  { id: "d61", text: "Change your notification sound to whatever I pick for a day.", category: "chaotic", intensity: "bold" },
  { id: "d62", text: "Read out the last thing you wrote in a group chat, with context.", category: "embarrassing", intensity: "bold" },
  { id: "d63", text: "Tell me something you've been overthinking this week.", category: "relationship", intensity: "bold" },
  { id: "d64", text: "Look at me and say nothing for thirty seconds.", category: "flirty", intensity: "bold" },
  { id: "d65", text: "Kiss me somewhere you don't usually.", category: "flirty", intensity: "bold" },
  { id: "d66", text: "Describe what you'd do on a perfect day with me, hour by hour.", category: "flirty", intensity: "bold" },

  // chaotic — still harmless, still doable indoors
  { id: "d67", text: "Let me redecorate one shelf however I like. It stays until tomorrow.", category: "chaotic", intensity: "chaotic" },
  { id: "d68", text: "Swap one item of clothing with me for the next three rounds.", category: "chaotic", intensity: "chaotic" },
  { id: "d69", text: "Speak in a fake accent until your next turn.", category: "chaotic", intensity: "chaotic" },
  { id: "d70", text: "Let me style your hair. No mirror until it's done.", category: "chaotic", intensity: "chaotic" },
  { id: "d71", text: "Do the next three rounds standing on one leg.", category: "chaotic", intensity: "chaotic" },
  { id: "d72", text: "Build the tallest structure you can from things within arm's reach. Sixty seconds.", category: "chaotic", intensity: "chaotic" },
  { id: "d73", text: "Let me give you a new middle name. Use it for the rest of the game.", category: "chaotic", intensity: "chaotic" },
  { id: "d74", text: "Eat or drink whatever I hand you next. Nothing horrible, I promise.", category: "chaotic", intensity: "chaotic" },
  { id: "d75", text: "Give a wedding toast for two objects in this room that are clearly in love.", category: "chaotic", intensity: "chaotic" },
  { id: "d76", text: "Let me set your phone wallpaper. It stays for 24 hours.", category: "chaotic", intensity: "chaotic" },
  { id: "d77", text: "Answer everything in rhyme until your next turn.", category: "chaotic", intensity: "chaotic" },
  { id: "d78", text: "Wear something of mine for the rest of the game.", category: "chaotic", intensity: "chaotic" },
  { id: "d79", text: "Give a passionate two-minute speech defending a terrible opinion.", category: "chaotic", intensity: "chaotic" },
  { id: "d80", text: "Let me draw on your hand with a pen. My choice.", category: "chaotic", intensity: "chaotic" },
  { id: "d81", text: "Reorganise one drawer in ninety seconds. I'm timing you.", category: "chaotic", intensity: "chaotic" },
  { id: "d82", text: "Take a photo of us right now that we're both contractually obliged to keep.", category: "chaotic", intensity: "chaotic" },
  { id: "d83", text: "Make up a completely fake but convincing fact and defend it for a minute.", category: "chaotic", intensity: "chaotic" },
  { id: "d84", text: "Do everything with your non-dominant hand until your next turn.", category: "chaotic", intensity: "chaotic" },
  { id: "d85", text: "Whisper for the next three rounds. No exceptions.", category: "chaotic", intensity: "chaotic" },
  { id: "d86", text: "Give me a full weather forecast for our week, invented.", category: "chaotic", intensity: "chaotic" },
  { id: "d87", text: "Pick a household object and pitch it as a luxury product for sixty seconds.", category: "chaotic", intensity: "chaotic" },
  { id: "d88", text: "Let me choose the music for the next thirty minutes. No complaints.", category: "chaotic", intensity: "chaotic" },
  { id: "d89", text: "Explain your job to me as though it's secretly very sinister.", category: "chaotic", intensity: "chaotic" },
  { id: "d90", text: "Act out your entire morning routine at four times speed, including the bits you skip.", category: "chaotic", intensity: "chaotic" },
  { id: "d91", text: "Give the room a five-star review as if it were a hotel.", category: "chaotic", intensity: "chaotic" },
  { id: "d92", text: "Take on a completely new personality for two rounds. Commit.", category: "chaotic", intensity: "chaotic" },
  { id: "d93", text: "Let me add one contact name emoji to your phone.", category: "chaotic", intensity: "chaotic" },
  { id: "d94", text: "Do the worst possible job of making tea, and narrate it.", category: "chaotic", intensity: "chaotic" },
  { id: "d95", text: "Invent and perform a theme tune for this room.", category: "chaotic", intensity: "chaotic" },
  { id: "d96", text: "Recap the plot of a film you've never seen, entirely from the title, with total confidence.", category: "chaotic", intensity: "chaotic" },
  { id: "d97", text: "Convince me you're a ghost who's just realised it.", category: "chaotic", intensity: "chaotic" },
  { id: "d98", text: "Give a eulogy for the last thing you broke.", category: "chaotic", intensity: "chaotic" },
  { id: "d99", text: "Text one person 'I've made a decision' and then don't explain for an hour.", category: "chaotic", intensity: "chaotic" },
  { id: "d100", text: "Let me pick your next meal, entirely. You may not negotiate.", category: "chaotic", intensity: "chaotic" },
  { id: "d101", text: "Leave me a passive-aggressive voicemail about something trivial. Two takes maximum.", category: "funny", intensity: "bold" },
  { id: "d102", text: "Deliver a eulogy for the last thing you lost. Make me feel something.", category: "funny", intensity: "chill" },
  { id: "d103", text: "Do a full infomercial for the least impressive thing you own. Include a price.", category: "funny", intensity: "chill" },
  { id: "d104", text: "Defend a small crime you've committed in front of an imaginary jury. I'm the judge.", category: "chaotic", intensity: "bold" },
  { id: "d105", text: "Give the weather forecast for your emotional state this week, with a map.", category: "funny", intensity: "chill" },
  { id: "d106", text: "Teach me something you actually know, badly, in ninety seconds.", category: "funny", intensity: "chill" },
  { id: "d107", text: "Narrate my next sixty seconds as a wildlife commentator. I will be doing nothing.", category: "funny", intensity: "chill" },
  { id: "d108", text: "Do an impression of me arriving home after a bad day. Be accurate, not kind.", category: "relationship", intensity: "bold" },
];

export const promptsFor = (pool: Prompt[], intensities: PromptIntensity[]) =>
  intensities.length ? pool.filter((p) => intensities.includes(p.intensity)) : pool;
