import "server-only";

/**
 * The object-storage contract.
 *
 * Deliberately small, and deliberately not S3-shaped: presign, verify, fetch a
 * prefix of the bytes, delete. Everything the experiences need is expressed in
 * those four, so replacing R2 later means writing one file — not touching
 * Photobooth or Snap Hunt.
 *
 * Object keys are always generated by the server. No implementation accepts a
 * key from a request, which is what makes path traversal a non-question rather
 * than a validation problem.
 */

export interface PresignedUpload {
  /** Where the client PUTs the bytes. Short-lived. */
  url: string;
  /** Headers the client must send for the signature to match. */
  headers: Record<string, string>;
  expiresAt: number;
}

export interface StoredObject {
  bytes: number;
  contentType: string;
}

export interface ObjectStore {
  /** Names the backend, for diagnostics and the health endpoint. */
  readonly kind: "r2" | "local";

  /** A URL the client may PUT one object to, for a few minutes. */
  presignUpload(key: string, contentType: string, maxBytes: number): Promise<PresignedUpload>;

  /** A URL the client may GET one object from, for a while. */
  presignDownload(key: string, ttlSeconds: number): Promise<string>;

  /**
   * Size and the *first bytes* of a stored object.
   *
   * The first bytes are the point: with a presigned PUT the server never sees
   * the upload, so this is where what actually landed gets inspected rather
   * than what the client said it was sending.
   */
  head(key: string, prefixBytes: number): Promise<{ object: StoredObject; prefix: Uint8Array } | null>;

  remove(keys: string[]): Promise<void>;
}

/** How long an upload URL stays valid. Long enough for a slow phone, short enough to matter. */
export const UPLOAD_TTL_SECONDS = 300;

/** How long a download URL stays valid. */
export const DOWNLOAD_TTL_SECONDS = 900;
